# Generated by Django 3.2.9 on 2021-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='tutor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
