# Generated by Django 3.2.9 on 2021-12-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='reveiw_rating',
            new_name='review_rating',
        ),
        migrations.RenameField(
            model_name='coursereview',
            old_name='reveiw_text',
            new_name='review_text',
        ),
    ]
