# Generated by Django 3.2.9 on 2021-12-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='review_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=150),
        ),
    ]
