# Generated by Django 3.2.9 on 2021-12-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursereview_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='review_text',
            field=models.CharField(max_length=160),
        ),
    ]
