# Generated by Django 3.2.9 on 2021-12-09 17:31

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_userlibrary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ('name',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='order_id',
            field=models.CharField(blank=True, default=products.models.random_code, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='reference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
