# Generated by Django 3.2.9 on 2021-12-09 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_alter_userlibrary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='courses',
            field=models.ManyToManyField(to='courses.Courses'),
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='user',
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='user',
            field=models.ManyToManyField(related_name='library', to=settings.AUTH_USER_MODEL),
        ),
    ]
