# Generated by Django 3.2.9 on 2021-12-09 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_auto_20211209_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlibrary',
            name='user',
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='library', to='users.user'),
            preserve_default=False,
        ),
    ]
