# Generated by Django 3.2.9 on 2021-12-11 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_userlibrary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
