# Generated by Django 3.2.9 on 2021-12-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.UUIDField(default='csd-ytr5436hg-6hhfr', primary_key=True, serialize=False),
        ),
    ]
