# Generated by Django 3.2.9 on 2021-12-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_courses_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
