# Generated by Django 3.2.9 on 2021-12-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_userlibrary_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ('id',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'ordering': ('id',), 'verbose_name_plural': 'UserLibraries'},
        ),
    ]
