# Generated by Django 3.2.9 on 2021-12-13 14:31

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20211213_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_pdf',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.pdf_directory),
        ),
    ]
