# Generated by Django 3.2.9 on 2021-12-13 16:54

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_courses_course_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_video',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.video_directory),
        ),
    ]
