# Generated by Django 3.2.9 on 2021-12-13 17:20

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_courses_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_pdf',
            field=models.FileField(default=True, upload_to=courses.models.pdf_directory),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_video',
            field=models.FileField(default=True, upload_to=courses.models.video_directory),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(default=True, max_length=250, unique_for_date='created'),
            preserve_default=False,
        ),
    ]
